name: profiling
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=0.24.2
- conda-forge::pip=19.2.2
- pip
- pip:
  - git+https://github.com/cytomining/pycytominer@820a8369ab7d49be118d73e9074f998739eab325
