name: profiling
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=1.2.0
- conda-forge::pip=19.2.2
- conda-forge::pyyaml=5.3.1
- conda-forge::plotly=4.14.3
- plotly::python-kaleido=0.0.3
- pip
- pip:
  - git+https://github.com/cytomining/pycytominer@fae2764721be7b9a7227e404cf9c09764a55789d
